/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportsandroads.gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author john
 */
public class CollectData extends javax.swing.JFrame {

    private int[][] costs;
    private boolean alReady = false;

    /**
     * Creates new form collectData
     */
    public CollectData() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        init();
    }

    private void init() {
        listeners();
        TMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TMatrix.getTableHeader().setReorderingAllowed(false);
        TMatrix.setTableHeader(null); //Doesn't Work!!
    }

    private void listeners() {
        tCities.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (c != '0' && c != '1' && c != '2' && c != '3' && c != '4' && c != '5' && c != '6' && c != '7' && c != '8' && c != '9') {
                    e.consume();  // ignore event
                }
            }
        });
    }

    private void generateTable() {
        if (tCities.getText() != "0") {
            DefaultTableModel model = (DefaultTableModel) TMatrix.getModel();

            model.setRowCount(Integer.valueOf(tCities.getText()));
            //model.setColumnCount(Integer.valueOf(tCities.getText()));
            model.setColumnCount(0);

            //Object[] blank = new Object[Integer.valueOf(tCities.getText())];
            //Arrays.fill(blank, -1);
            for (int i = 0; i < Integer.valueOf(tCities.getText()); i++) {
                model.addColumn(i);
            }

            costs = new int[Integer.valueOf(tCities.getText())][Integer.valueOf(tCities.getText())];
            //for (int i = 0; i < Integer.valueOf(tCities.getText()); i++) {
            //    model.addRow(blank);
            //}
        }
    }

    private void fillMatrix() {
        DefaultTableModel model = (DefaultTableModel) TMatrix.getModel();
        for (int i = 0; i < TMatrix.getRowCount(); i++) {
            for (int j = 0; j < i + 1; j++) {
                int cost;
                try {
                    cost = Integer.valueOf(model.getValueAt(i, j).toString());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ingrese bien la matriz.");
                    return;
                }
                model.setValueAt(cost, j, i);
                costs[i][j] = costs[j][i] = cost;
            }
        }
        alReady = true;
        JOptionPane.showMessageDialog(null, "Espere!");
    }

    public int[][] getCostsMatrix() {
        return costs;
    }

    public int getCities() {
        return Integer.valueOf(tCities.getText());
    }

    public boolean alReady() {
        return alReady;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TMatrix = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tCities = new javax.swing.JTextField();
        bEnter = new javax.swing.JButton();
        bHelp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Costos");
        setResizable(false);

        TMatrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TMatrix.getTableHeader().setResizingAllowed(false);
        TMatrix.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TMatrix);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Digite el numero de ciudades");

        tCities.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tCities.setText("0");

        bEnter.setText("Aceptar");
        bEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnterActionPerformed(evt);
            }
        });

        bHelp.setText("Ayuda");
        bHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHelpActionPerformed(evt);
            }
        });

        jButton1.setText("Terminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tCities, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCities, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEnter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bHelp))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnterActionPerformed
        generateTable();
    }//GEN-LAST:event_bEnterActionPerformed

    private void bHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHelpActionPerformed
        JOptionPane.showMessageDialog(null, "Para ingresar los costos:\n En la diagonal principal pondra los costos de los aereopuertos, y abajo de la diagonal los costos de los caminos. Nosotros haremos la matriz simetrica. \n Si la matriz esta bien ingresada pero le dice que la ingrese bien revise que no tenga una casilla activada o focuseada para seguir escribiendo.");
    }//GEN-LAST:event_bHelpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillMatrix();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TMatrix;
    private javax.swing.JButton bEnter;
    private javax.swing.JButton bHelp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCities;
    // End of variables declaration//GEN-END:variables
}
